package com.zhaojufei.practice.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dm_equipment_app
 */
public class dmEquipmentAppDo {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   应用ID,UUID（由于业务方使用设备id+应用类型确定一个应用，这个id系统生成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     * Database Column Remarks:
     *   商户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * Database Column Remarks:
     *   门店ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.store_id
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     * Database Column Remarks:
     *   设备ID,逻辑外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.equipment_id
     *
     * @mbg.generated
     */
    private String equipmentId;

    /**
     * Database Column Remarks:
     *   应用类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.app_type
     *
     * @mbg.generated
     */
    private String appType;

    /**
     * Database Column Remarks:
     *   最近心跳时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.heart_beat_time
     *
     * @mbg.generated
     */
    private Date heartBeatTime;

    /**
     * Database Column Remarks:
     *   应用名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     * Database Column Remarks:
     *   应用版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.app_version
     *
     * @mbg.generated
     */
    private String appVersion;

    /**
     * Database Column Remarks:
     *   应用大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.app_size
     *
     * @mbg.generated
     */
    private BigDecimal appSize;

    /**
     * Database Column Remarks:
     *   应用是否在运行: 1 运行，0 未运行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.run_flag
     *
     * @mbg.generated
     */
    private Byte runFlag;

    /**
     * Database Column Remarks:
     *   应用运行状态： ok:正常，error（异常）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.app_status
     *
     * @mbg.generated
     */
    private String appStatus;

    /**
     * Database Column Remarks:
     *   端口信息：端口信息，自定义格式，字符串类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.port_info
     *
     * @mbg.generated
     */
    private String portInfo;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   逻辑删除标识：0未删除，1已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_equipment_app.delete_flag
     *
     * @mbg.generated
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.id
     *
     * @return the value of dm_equipment_app.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.id
     *
     * @param id the value for dm_equipment_app.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.app_id
     *
     * @return the value of dm_equipment_app.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.app_id
     *
     * @param appId the value for dm_equipment_app.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.tenant_id
     *
     * @return the value of dm_equipment_app.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.tenant_id
     *
     * @param tenantId the value for dm_equipment_app.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.store_id
     *
     * @return the value of dm_equipment_app.store_id
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.store_id
     *
     * @param storeId the value for dm_equipment_app.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.equipment_id
     *
     * @return the value of dm_equipment_app.equipment_id
     *
     * @mbg.generated
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.equipment_id
     *
     * @param equipmentId the value for dm_equipment_app.equipment_id
     *
     * @mbg.generated
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.app_type
     *
     * @return the value of dm_equipment_app.app_type
     *
     * @mbg.generated
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.app_type
     *
     * @param appType the value for dm_equipment_app.app_type
     *
     * @mbg.generated
     */
    public void setAppType(String appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.heart_beat_time
     *
     * @return the value of dm_equipment_app.heart_beat_time
     *
     * @mbg.generated
     */
    public Date getHeartBeatTime() {
        return heartBeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.heart_beat_time
     *
     * @param heartBeatTime the value for dm_equipment_app.heart_beat_time
     *
     * @mbg.generated
     */
    public void setHeartBeatTime(Date heartBeatTime) {
        this.heartBeatTime = heartBeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.app_name
     *
     * @return the value of dm_equipment_app.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.app_name
     *
     * @param appName the value for dm_equipment_app.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.app_version
     *
     * @return the value of dm_equipment_app.app_version
     *
     * @mbg.generated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.app_version
     *
     * @param appVersion the value for dm_equipment_app.app_version
     *
     * @mbg.generated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.app_size
     *
     * @return the value of dm_equipment_app.app_size
     *
     * @mbg.generated
     */
    public BigDecimal getAppSize() {
        return appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.app_size
     *
     * @param appSize the value for dm_equipment_app.app_size
     *
     * @mbg.generated
     */
    public void setAppSize(BigDecimal appSize) {
        this.appSize = appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.run_flag
     *
     * @return the value of dm_equipment_app.run_flag
     *
     * @mbg.generated
     */
    public Byte getRunFlag() {
        return runFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.run_flag
     *
     * @param runFlag the value for dm_equipment_app.run_flag
     *
     * @mbg.generated
     */
    public void setRunFlag(Byte runFlag) {
        this.runFlag = runFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.app_status
     *
     * @return the value of dm_equipment_app.app_status
     *
     * @mbg.generated
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.app_status
     *
     * @param appStatus the value for dm_equipment_app.app_status
     *
     * @mbg.generated
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.port_info
     *
     * @return the value of dm_equipment_app.port_info
     *
     * @mbg.generated
     */
    public String getPortInfo() {
        return portInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.port_info
     *
     * @param portInfo the value for dm_equipment_app.port_info
     *
     * @mbg.generated
     */
    public void setPortInfo(String portInfo) {
        this.portInfo = portInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.create_time
     *
     * @return the value of dm_equipment_app.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.create_time
     *
     * @param createTime the value for dm_equipment_app.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.modify_time
     *
     * @return the value of dm_equipment_app.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.modify_time
     *
     * @param modifyTime the value for dm_equipment_app.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_equipment_app.delete_flag
     *
     * @return the value of dm_equipment_app.delete_flag
     *
     * @mbg.generated
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_equipment_app.delete_flag
     *
     * @param deleteFlag the value for dm_equipment_app.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", storeId=").append(storeId);
        sb.append(", equipmentId=").append(equipmentId);
        sb.append(", appType=").append(appType);
        sb.append(", heartBeatTime=").append(heartBeatTime);
        sb.append(", appName=").append(appName);
        sb.append(", appVersion=").append(appVersion);
        sb.append(", appSize=").append(appSize);
        sb.append(", runFlag=").append(runFlag);
        sb.append(", appStatus=").append(appStatus);
        sb.append(", portInfo=").append(portInfo);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    public static dmEquipmentAppDo.Builder builder() {
        return new dmEquipmentAppDo.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private dmEquipmentAppDo obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new dmEquipmentAppDo();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.id
         *
         * @param id the value for dm_equipment_app.id
         *
         * @mbg.generated
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.app_id
         *
         * @param appId the value for dm_equipment_app.app_id
         *
         * @mbg.generated
         */
        public Builder appId(String appId) {
            obj.setAppId(appId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.tenant_id
         *
         * @param tenantId the value for dm_equipment_app.tenant_id
         *
         * @mbg.generated
         */
        public Builder tenantId(String tenantId) {
            obj.setTenantId(tenantId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.store_id
         *
         * @param storeId the value for dm_equipment_app.store_id
         *
         * @mbg.generated
         */
        public Builder storeId(String storeId) {
            obj.setStoreId(storeId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.equipment_id
         *
         * @param equipmentId the value for dm_equipment_app.equipment_id
         *
         * @mbg.generated
         */
        public Builder equipmentId(String equipmentId) {
            obj.setEquipmentId(equipmentId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.app_type
         *
         * @param appType the value for dm_equipment_app.app_type
         *
         * @mbg.generated
         */
        public Builder appType(String appType) {
            obj.setAppType(appType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.heart_beat_time
         *
         * @param heartBeatTime the value for dm_equipment_app.heart_beat_time
         *
         * @mbg.generated
         */
        public Builder heartBeatTime(Date heartBeatTime) {
            obj.setHeartBeatTime(heartBeatTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.app_name
         *
         * @param appName the value for dm_equipment_app.app_name
         *
         * @mbg.generated
         */
        public Builder appName(String appName) {
            obj.setAppName(appName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.app_version
         *
         * @param appVersion the value for dm_equipment_app.app_version
         *
         * @mbg.generated
         */
        public Builder appVersion(String appVersion) {
            obj.setAppVersion(appVersion);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.app_size
         *
         * @param appSize the value for dm_equipment_app.app_size
         *
         * @mbg.generated
         */
        public Builder appSize(BigDecimal appSize) {
            obj.setAppSize(appSize);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.run_flag
         *
         * @param runFlag the value for dm_equipment_app.run_flag
         *
         * @mbg.generated
         */
        public Builder runFlag(Byte runFlag) {
            obj.setRunFlag(runFlag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.app_status
         *
         * @param appStatus the value for dm_equipment_app.app_status
         *
         * @mbg.generated
         */
        public Builder appStatus(String appStatus) {
            obj.setAppStatus(appStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.port_info
         *
         * @param portInfo the value for dm_equipment_app.port_info
         *
         * @mbg.generated
         */
        public Builder portInfo(String portInfo) {
            obj.setPortInfo(portInfo);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.create_time
         *
         * @param createTime the value for dm_equipment_app.create_time
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.modify_time
         *
         * @param modifyTime the value for dm_equipment_app.modify_time
         *
         * @mbg.generated
         */
        public Builder modifyTime(Date modifyTime) {
            obj.setModifyTime(modifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column dm_equipment_app.delete_flag
         *
         * @param deleteFlag the value for dm_equipment_app.delete_flag
         *
         * @mbg.generated
         */
        public Builder deleteFlag(Byte deleteFlag) {
            obj.setDeleteFlag(deleteFlag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public dmEquipmentAppDo build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        appId("app_id", "appId", "VARCHAR", false),
        tenantId("tenant_id", "tenantId", "VARCHAR", false),
        storeId("store_id", "storeId", "VARCHAR", false),
        equipmentId("equipment_id", "equipmentId", "VARCHAR", false),
        appType("app_type", "appType", "VARCHAR", false),
        heartBeatTime("heart_beat_time", "heartBeatTime", "TIMESTAMP", false),
        appName("app_name", "appName", "VARCHAR", false),
        appVersion("app_version", "appVersion", "VARCHAR", false),
        appSize("app_size", "appSize", "DECIMAL", false),
        runFlag("run_flag", "runFlag", "TINYINT", false),
        appStatus("app_status", "appStatus", "VARCHAR", false),
        portInfo("port_info", "portInfo", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        deleteFlag("delete_flag", "deleteFlag", "TINYINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dm_equipment_app
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}