server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: zhaojufei123
    # 连接池初始化大小
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml            # mybatis配置文件所在路径
  type-aliases-package: com.zhaojufei.practice.web.entity       # 定义所有操作类的别名所在包
  mapper-locations:
    classpath:mybatis/mapper/*.xml
