package com.zhaojufei.practice.dao;

import com.zhaojufei.practice.entity.dmEquipmentAppDo;
import com.zhaojufei.practice.entity.dmEquipmentAppDoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface dmEquipmentAppDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    long countByExample(dmEquipmentAppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int deleteByExample(dmEquipmentAppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int insert(dmEquipmentAppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int insertSelective(dmEquipmentAppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    dmEquipmentAppDo selectOneByExample(dmEquipmentAppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    List<dmEquipmentAppDo> selectByExample(dmEquipmentAppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    dmEquipmentAppDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") dmEquipmentAppDo record, @Param("example") dmEquipmentAppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") dmEquipmentAppDo record, @Param("example") dmEquipmentAppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(dmEquipmentAppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(dmEquipmentAppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<dmEquipmentAppDo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_equipment_app
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<dmEquipmentAppDo> list, @Param("selective") dmEquipmentAppDo.Column ... selective);
}